### ISSUE TITLE
DiskAvailable: Possible memory leak?

### ISSUE THREAD

**Issue by cbasavaraj** [pytorch/serve#771] opened 2020-11-03 14:57 UTC
Hi, I'm new to TorchServe, started only yesterday, but since then I've noticed that it's consuming space on my hard disk quite rapidly. Please see two screenshots attached, two hours apart, and I wasn't even running TS all the time.

## Context
* torchserve version: 0.2.0
* torch version: 1.6.0
* torchvision version [if any]: 0.7.0
* torchtext version [if any]: --
* torchaudio version [if any]: --
* java version: openjdk-11-jdk
* Operating System and version: Ubuntu 18.04.5 LTS

## Your Environment
* Installed using source? [yes/no]: No
* Are you planning to deploy it using docker container? [yes/no]: Maybe
* Is it a CPU or GPU environment?: 2 GPUs
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom handler (see below)
* What kind of model is it e.g. vision, text, audio?: detectron2 object detection model
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?: local model
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]: --

![13h30](https://user-images.githubusercontent.com/15706875/98000446-c9cbdc00-1dec-11eb-9724-a5418ac03320.png)
![15h30](https://user-images.githubusercontent.com/15706875/98000457-ccc6cc80-1dec-11eb-8eb9-1e75466ff29a.png)

## Custom Handler
```
class d2Handler(object):
    """TorchServe Handler for detectron2."""

    def __init__(self):
        """Construct a d2Handler."""
        self.logger = logging.getLogger(__name__)

        self.device = 'cpu'
        self.initialized = False

    def initialize(self, context):
        """Initialize model.

        Args:
            context: TorchServe context.
        """
        self.context = context
        if CUDA:
            self.device = "cuda:" + \
                str(self.context.system_properties.get('gpu_id'))
        self.cfg = setup_cfg('test', self.device)
        self.predictor = BatchPredictor(self.cfg)
        self.initialized = True
        self.logger.info("Model initialized.")

    def preprocess(self, requests):
        """Transform http requests into images."""
        images = []
        for request in requests:
            image = request.get('body')
            image = io.BytesIO(image)
            image = np.frombuffer(image.read(), np.uint8)
            image = cv2.imdecode(image, cv2.IMREAD_COLOR)
            images.append(image)
        return images

    def inference(self, images):
        """Perform inference on images."""
        return self.predictor(images)

    def postprocess(self, preds):
        """Serialize model preds."""
        rstrings = []
        for pred in preds:
            insts = pred['instances'].to('cpu')
            rdict = {
                'bboxes': insts.pred_boxes.tensor.numpy(),
                'labels': insts.pred_classes.numpy(),
                'scores': insts.full_scores.numpy(),
                'smasks': encode(insts.pred_masks.numpy().astype(np.uint8)),
                'featrs': insts.features.numpy()
            }
            rstrings.append(
                orjson.dumps(rdict, option=orjson.OPT_SERIALIZE_NUMPY)
            )
        return rstrings

    def handle(self, data, context):
        """Handle."""
        self.context = context
        metrics = self.context.metrics

        data = self.preprocess(data)
        tic = time.time()
        data = self.inference(data)
        toc = time.time()
        data = self.postprocess(data)

        metrics.add_time('InferenceTime', round((toc - tic) * 1000, 2))

        return data
```

## Custom Config
```
model_store=data/store
inference_address=https://0.0.0.0:8443
management_address=https://0.0.0.0:8444
metrics_address=https://0.0.0.0:8445
private_key_file=certs/my.key
certificate_file=certs/my.pem
```

**Comment by harshbafna** [comment] 2020-11-03 15:21
@cbasavaraj: TorchServe will only consume disk space for the following:

 - Model temp dir: temporary location where model-archive is extracted 
 - Model store: Where model-archives are stored (downloaded in case a public URL is specified)
 - Logs: 
   - System metrics are logged every minute by default
   - API access logs
   - Server logs
   - Model metrics

Assuming you have only one model registered, none of the above should consume ~2GB of disk space in ~2 hours time span, once the model has been registered.

Questions:

 - What happens to the prediction output returned from TorchServe. Are you plotting the segments and saving as an image?
 - Is there any other activity that has happened in the meanwhile like any other download activity, docker image pull?

**Comment by cbasavaraj** [comment] 2020-11-03 17:54
Found the problem! Like you said, it's the `/tmp/models` directory which is causing the problem. As I've been experimenting / prototyping, I've stopped and started TorchServe many many times, and turns out that all the extracted models are retained. It's 15.1 GB now (that's 30 times x a 500 MB model). Apart from clearing `/tmp/models` manually, is there anything we could do differently with TorchServe?

**Comment by harshbafna** [comment] 2020-11-04 04:22
@cbasavaraj: Thanks for confirming the root cause of the problem. The model temp directory is cleaned whenever a model is unregistered. As part of windows native support, we now unregister every model while [stopping TorchServe](https://github.com/pytorch/serve/pull/662/files#diff-45f9e03a9d3046ef0e2c18e18b0bb9c1889f9e3ff9918568870539cc926e3895R391). So this issue will get fixed with the next release of TorchServe.

**Comment by cbasavaraj** [comment] 2020-11-04 09:46
Thanks. Not sure what "windows native support" means though, does it apply to Ubuntu or Linux in general as well?
And a couple of other general questions:
a) Why is Java being used as opposed to C++? Just curious.
b) What do you think of nvidia's Triton Inference Server. They seem to be a bit more advanced than TorchServe? I hope TorchServe will be great, because in general I'm happy with PyTorch and wouldn't want to move.

**Comment by harshbafna** [comment] 2020-11-05 15:47
@cbasavaraj: 

> Not sure what "windows native support" means though, 

We are adding support for running TorchServe on the windows box. In the last release, TorchServe was certified on WSL on windows. 

> does it apply to Ubuntu or Linux in general as well?

The said changes are generic and will apply to all the OS.

> a) Why is Java being used as opposed to C++? Just curious.

The project was derived from the [Multi-Model Server (MMS)](https://github.com/awslabs/multi-model-server)


> b) What do you think of nvidia's Triton Inference Server. They seem to be a bit more advanced than TorchServe? I hope TorchServe will be great, because in general I'm happy with PyTorch and wouldn't want to move.

There is a lot of difference between the way TorchServe and Triton host models and run inference. Following are some of the extra features of TorchServe:

 - provides a bunch of [default handlers](https://github.com/pytorch/serve/blob/master/docs/default_handlers.md) out-of-box
 - provides the option of server-side pre-processing and post-processing through [custom handlers](https://github.com/pytorch/serve/blob/master/docs/custom_service.md)
 - supports both Eager and TorchScript models
 - supports model versioning
 - supports [model snapshot](https://github.com/pytorch/serve/blob/master/docs/snapshot.md)

Upcoming features/enhancements

 - [support for gRPC APIs](https://github.com/pytorch/serve/pull/687)
 - [ensemble workflow support](https://github.com/pytorch/serve/issues/682)
 - [windows native support](https://github.com/pytorch/serve/pull/662)
 - [Multiserving framework integration like Seldon, KFServing](https://github.com/pytorch/serve/pull/749)
 - [Plugin based metric API framework](https://github.com/pytorch/serve/pull/763)

**Comment by cbasavaraj** [comment] 2020-11-09 12:29
Thanks for all the responses. I have one more question related to workers. In order to economise on GPU memory usage, is it possible to load a given model only once, and make it usable by multiple workers? If this is possible, it'll be much easier to scale up. Thanks

**Comment by harshbafna** [comment] 2020-11-09 13:40
> Thanks for all the responses. I have one more question related to workers. In order to economise on GPU memory usage, is it possible to load a given model only once, and make it usable by multiple workers? If this is possible, it'll be much easier to scale up. Thanks

As per the current framework, each model worker is a process and there is no possible way to share the model(s) across these processes. We are currently evaluating various options to optimize the memory usage of model workers. We are tracking this through #733.

**Comment by misrasaurabh1** [comment] 2020-11-20 05:08
@harshbafna The reply https://github.com/pytorch/serve/issues/771#issuecomment-722461177 should be added to a FAQ. I learnt a lot about the design choices through this comment

**Comment by harshbafna** [comment] 2020-11-25 12:01
Closing this as the fix related to model temp dir is merged to master.

**Closed by harshbafna** 2020-11-25 12:01 UTC
Labels: triaged_wait
