### ISSUE TITLE
Port forwarding fails when using the --ts-config flag and the relevant config.properties file in docker environment

### ISSUE THREAD

**Issue by dmuiruri** [pytorch/serve#1626] opened 2022-05-12 18:55 UTC
Please have a look at [FAQ's](../../docs/FAQs.md) and [Troubleshooting guide](../../docs/Troubleshooting.md), your query may be already addressed.

Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

I tried starting a Torchserve container and forward the ports (inference, metrics etc) to the host machine (Ubuntu VM) but I cannot access the endpoints from the host machine (<ipaddress>:8080/ping) but they are accessible from inside the container (localhost:8080/ping).
docker run --rm -it -p8080:8080 -p8081:8081 -p8082:8082 -p7070:7070 -p7071:7071 --name tserve -v $(pwd)/tsconfig:/home/config -v $(pwd)/model-store:/home/model-server/model-store -v $(pwd)/examples:/home/model-server/examples  pytorch/torchserve:latest-cpu torchserve --ts-config /home/config/config.properties

* torchserve version:  0.5.2b20211229
* torch-model-archiver version: 0.5.2b20211229
* torch version: 1.10.0+cpu
* torchvision version [if any]: 0.11.1+cpu
* torchtext version [if any]: 0.11.0
* torchaudio version [if any]: 0.10.0+cpu
* java version:
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

* Operating System and version:Ubuntu, 18.04, bionic

## Your Environment

* Installed using source? [yes/no]:no
* Are you planning to deploy it using docker container? [yes/no]:yes
* Is it a CPU or GPU environment?:cpu
* Using a default/custom handler? [If possible upload/share custom handler/model]:
* What kind of model is it e.g. vision, text, audio?:vision(image classification)
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: model-store
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
inference_address=http://127.0.0.1:8080
management_address=http://127.0.0.1:8081
metrics_address=http://127.0.0.1:8082
grpc_inference_port=7070
grpc_management_port=7071
model_store=model-store
load_models=all
enable_metrics_api=true

* Link to your project [if any]:

## Expected Behavior

Ability to reach endpoints from host machine and public ip address
curl ipadrress:8081/models

## Current Behavior

Using the --ts-config flag a config.properties file the torchserve endpoints are not accessible outside of the container
curl: (56) Recv failure: Connection reset by peer

Removing these lines below from the config.properties file does not change the error behavior
inference_address=http://127.0.0.1:8080
management_address=http://127.0.0.1:8081
metrics_address=http://127.0.0.1:8082
grpc_inference_port=7070
grpc_management_port=7071

## Possible Solution

Supplying all configurations from command line (i.e not using --ts-config file), the endpoints become accessible through port forwarding.

## Steps to Reproduce

1. Deploy a torchserve container where the configurations of the server are contained in the config.properties with port forwarding
docker run --rm -it -p8080:8080 -p8081:8081 -p8082:8082 -p7070:7070 -p7071:7071 --name tserve -v $(pwd)/tsconfig:/home/config -v $(pwd)/model-store:/home/model-server/model-store -v $(pwd)/examples:/home/model-server/examples  pytorch/torchserve:latest-cpu torchserve --ts-config /home/config/config.properties

2. Access the endpoint from the host machine (localhost:8080/ping) or a public IP if the VM has a public IP
3. Try to access the endpoints from inside the container (this should be at least successful)
...

**Comment by amit-cashify** [comment] 2022-06-29 02:09
> I will look into it and get back @amit-cashify 

Thanks

**Comment by agunapal** [comment] 2022-06-30 19:56
@amit-cashify @dmuiruri can you please share your config.properties so I can reproduce it accurately. Also, is pwd the serve directory?

**Comment by agunapal** [comment] 2022-07-07 02:06
Yes @amit-cashify , I started the container with the following command
sudo docker run --rm -it -p 8080:8080 -p 8081:8081 -p 8082:8082 -p 7070:7070 -p 7071:7071 -v $(pwd)/model_store:/home/model-server/model-store -v /home/ubuntu/serve/docker:/home/config pytorch/torchserve:latest-cpu torchserve --ts-config /home/config/config.properties

Then I did a ping from the host VM and it works

curl http://localhost:8080/ping
{
  "status": "Healthy"
}

**Comment by agunapal** [comment] 2022-07-07 02:12
Thank you for reporting the issue. Closing this issue . Please re-open if you notice the problem again.

**Closed by agunapal** 2022-07-07 02:12 UTC
Labels: support, docker

**Comment by nihiluis** [comment] 2023-04-19 15:56
I think this issue still persists. The issue did point me to the config.properties. Seems to be fixed after I added: `inference_address=http://0.0.0.0:8080`to the config.
