### ISSUE TITLE
number of batch response mismatched for models with custom handler

### ISSUE THREAD

**Issue by veronikayurchuk** [pytorch/serve#730] opened 2020-10-15 16:03 UTC
## Context

I want to serve a model that accepts 8 ordered images per each request and returns an output.
I wrote my custom handler, where a `preprocess` method collects images that are coming from request and forms a tensor with size [8, 3, H, W]. Next, it sends it to an `inference` method, where this tensor used as an input to my model.

I sent a single request and got the following error.

`2020-10-15 06:53:50,802 [INFO ] W-9001-mymodel_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - model: mymodel, number of batch response mismatched, expect: 1, got: 8.`

Trying to fix this issue, I thought that changing the batch size value would help.
I deleted my model and registered a new one with a new batch size.
`curl -X DELETE http://localhost:8081/models/mymodel`
`curl -X POST "localhost:8081/models?model_name=mymodel&url=mymodel.mar&batch_size=8&max_batch_delay=1000&initial_workers=4"`
and checked if it was applied 

`[
  {
    "modelName": "mymodel",
    "modelVersion": "1.0",
    "modelUrl": "fa.mar",
    "runtime": "python",
    "minWorkers": 4,
    "maxWorkers": 4,
    "batchSize": 8,
    "maxBatchDelay": 1000,
    "loadedAtStartup": false,
    "workers": [
      {
        "id": "9012",
        "startTime": "2020-10-15T06:53:51.466Z",
        "status": "READY",
        "gpu": false,
        "memoryUsage": 998322176
      },...`

Everything looks good and now `"batchSize": 8`

Next, I sent the same request again and got the same error.

`2020-10-15 06:57:12,616 [INFO ] W-9008-mymodel_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - model: mymodel, number of batch response mismatched, expect: 1, got: 8.`

* torchserve version: 0.2.0
* torch version: 1.6.0
* torchvision version [if any]: 0.7.0
* java version: java 14.0.2 2020-07-14
* Operating System and version: macOS, 10.15.6 

## Expected Behavior

I run a request with 8 images and get the output.

Ideally, knowing my GPU capacity(=80), I expect that setting batch_size to 10(=gpu capacity/number of images in every request) would work too.  In other words, by sending 10 requests simultaneously, torchserve would fully load my GPU and I would receive all 10 responses at the same time. 

## Current Behavior

Got an error `number of batch response mismatched, expect: 1, got: 8`

P.S. If I am doing it wrong and I should use another approach to handle requests with 8 ordered images, I would very much appreciate any help and advice!

**Comment by HamidShojanazeri** [comment] 2020-10-15 21:41
@veronikayurchuk I could not reproduce the issue with a custom handler, would you please share the handler/ minimal code to reproduce it.

**Comment by harshbafna** [comment] 2020-10-16 04:54
@veronikayurchuk: 

In TorchServe, batching happens at the server frontend, where the frontend creates a batch of `n` (configured model batch_size, in your case 8) from `n` input requests and passes it on to the model handler, and expects `n` response back from the handler.

IIUC, you are doing the following steps:

 - you are sending one single request with 8 images,
 - converting these images into tensors in your handler's `preprocess`
 - create a batch from the above tensors and pass it to the model for inference
 - return the inference response

In this case, TorchServe frontend creates a `batch` of size `1` as it receives a single request is configured `max_batch_delay` time and expects a response of the same size. Which is why you see the following error in logs:

```
number of batch response mismatched, expect: 1, got: 8.
```

There are a couple of approaches for resolving this issue :

 - **Option 1 (recommended)**: Send every image in an independent request. TorchServe frontend will create a batch from the number of requests received in configured `max_batch_delay` time and pass it on to the handler.

 - **Option 2**: If your use-case requires sending 8 images in one request only, then return a single list of outputs from your current handler.

**Comment by harshbafna** [comment] 2020-10-28 07:01
Closing as the query has been answered and no response from OP.

**Closed by harshbafna** 2020-10-28 07:01 UTC
Labels: triaged_wait

**Comment by ankita4AI** [comment] 2021-01-19 14:34
@veronikayurchuk was your problem resolved?
I faced the same issue, Since the number of request is still 1, which is inherently carrying 8 inputs.
Updating the postprocess method solved the issue. Since number of predictions will be equal to the number of inputs.
if we return a list of list, this issue will not persist.
Would love to know how you handled it.
Thanks

@harshbafna I have used gRPC with tensorflow serving and seen huge difference wrt inference time. Fail to observe any speedup here with the difference in the number of inputs. Is it because of the layer of handler in between? Can you share your insights on benchmarks/profiling so as to what is causing the delay.

**Comment by jaekookang** [comment] 2021-09-15 01:06
I had a similar issue but for a different reason,
```
number of batch response mismatched, expect: 1, got: 256
```
which was fixed by just returning a list of list for the prediction output in my postprocess method. Thank you.

**Comment by braindotai** [comment] 2021-12-18 06:08
@jaekookang @harshbafna @ankita4AI Im having a very hard time with batching in torchserve, and couldn't find any good official documentation about it other than just registering the model with batch size config.
As far as I know, in torchserve the batching is done in the frontend from multiple requests, but when I send multiple requests with single input I getting the following error

@osmanager @msaroufim on sending multiple requests, I'm getting this error:
```
model: face-detection, number of batch response mismatched, expect: 2, got: 1
```
below's my config file:
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
load_models=all
install_py_dep_per_model=true

models={\
  "face-detection": {\
    "1.0": {\
        "defaultVersion": true,\
        "marName": "face-detection.mar",\
        "minWorkers": 1,\
        "maxWorkers": 5,\
        "batchSize": 64,\
        "maxBatchDelay": 200,\
        "responseTimeout": 500\
    }\
  }\
}
```
And here's my handler:
```python
import base64
from ts.torch_handler.base_handler import BaseHandler
from torchvision import transforms
from PIL import Image
import cv2
import numpy as np
import logging

class ModelHandler(BaseHandler):
    def initialize(self, context):
        super().initialize(context)

        self.transform = transforms.Compose([
            transforms.Resize((72, 54)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ])

    def preprocess(self, data):
        encoded_bytes = data[0].get("data") or data[0].get("body")
        cv2_decoded_bytes = base64.b64decode(encoded_bytes)
        cv2_decoded = np.frombuffer(cv2_decoded_bytes, dtype = np.uint8)
        cv2_image = cv2.imdecode(cv2_decoded, 1)

        image = Image.fromarray(cv2_image)
        image = self.transform(image)

        return image.unsqueeze(0)

    def postprocess(self, inference_output):
        return [inference_output.tolist()] # im tryint returning list of list as many suggested but it doesn't solve the issue
```

Just using requests library to send the requests which is as simple as:
```python
response = requests.post("http://localhost:8080/predictions/face-detection/", data = cv2_encoded_bytes)
```
When I run this same script from 2 separate terminals I get the error saying batch response mismatched.

Thanks for your time.

**Comment by svats2k** [comment] 2022-02-16 07:29
@braindotai were you able to solve your batching issue? If so, please post your understanding / workaround / solution.

**Comment by Dcas89** [comment] 2023-03-08 08:50
> I had a similar issue but for a different reason,
> 
> ```
> number of batch response mismatched, expect: 1, got: 256
> ```
> 
> which was fixed by just returning a list of list for the prediction output in my postprocess method. Thank you.

I've had the same issue and have been trying to fix this as suggested here. This batch mismatch issue should be patched.

**Comment by lewj85** [comment] 2023-04-04 19:32
You need to cast it to/from bytes:
Server:
`return [output_array.tobytes()]`
Client:
`arr = np.frombuffer(response.content, dtype="float32")`

Or whatever datatype you had on the server side, if not float32.

The way to make that work with the `tolist()` function is to pickle that result (`tolist()` casts to a python list, which then needs to be serialized into bytes) and then unpickle at the client:

Server:
`return [pickle.dumps(output_array.tolist())]`
Client:
`result = pickle.loads(response.content)`

The important part is that it has to be in bytes, rather than any type of programming language object, in order to be transmitted across the network from server to client.
