### ISSUE TITLE
Model Management API doesn't work with S3 presigned URL

### ISSUE THREAD

**Issue by Iron-Stark** [pytorch/serve#1293] opened 2021-10-26 20:36 UTC
## Context
I am trying to use the management API with a S3 presigned URL to download and register a new model. This is the code snippet:

```
   def create_presigned_url(self, bucket_name, object_name, expiration=3600):
        """Generate a presigned URL to share an S3 object

        :param bucket_name: string
        :param object_name: string
        :param expiration: Time in seconds for the presigned URL to remain valid
        :return: Presigned URL as string. If error, returns None.
        """

        # Generate a presigned URL for the S3 object
        s3_client = boto3.client('s3')
        try:
            response = s3_client.generate_presigned_url('get_object',
                                                        Params={'Bucket': bucket_name,
                                                                'Key': object_name},
                                                        ExpiresIn=expiration)
        except ClientError as e:
            logging.error(e)
            return None

        # The response contains the presigned URL
        return response
presigned_uri = self.create_presigned_url(bucket_name, object_name)
response = requests.post("http://127.0.0.1:8081/models?url={}".format(presigned_uri))
```

Doing a normal GET on the presigned URI works but it doesn't work when used with the model management API. I tried all the workarounds mentioned in #669 but those are not giving any results as well. Can you please recommend what to do to make it work. Listing the errors I get in various situations:

Using the raw presigned URI:

```
{
  "code": 400,
  "type": "DownloadArchiveException",
  "message": "Failed to download archive from: https://log-analyzer-torchserve-mar.s3.amazonaws.com/test_service/stage/uw1/21_10_22_23_25/anomaly_detection_1634945079.8530345.mar?AWSAccessKeyId=****"
}
```

Replacing & with %26:

```
{
  "code": 400,
  "type": "DownloadArchiveException",
  "message": "Failed to download archive from: https://log-analyzer-torchserve-mar.s3.amazonaws.com/test_service/stage/uw1/21_10_26_00_23/anomaly_detection_1635207765.7685282.mar?AWSAccessKeyId=****&Signature=****=&x-amz-security-token=****&Expires=1635283752"
}
```

Using the torchserve 0.4.2-cpu docker image.

## Your Environment

* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom but unrelated to the issue.
* What kind of model is it e.g. vision, text, audio?: text
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: S3 bucket

## Expected Behavior
It should be able to download the model from S3 and register it.

## Current Behavior
Returning a 400

## Steps to Reproduce

1.  Just upload a mar file to a s3 bucket
2. Create the presigned uri using the given code and then call the managment API to try to register the model.
...

**Comment by mrcolo** [comment] 2021-12-15 01:22
any news on this one? having the same problem for 0.5.0

**Comment by lxning** [comment] 2021-12-15 02:03
@mrcolo your s3 url contains aws acceskey and password. it is not safe to include them in url. I guess that's why TS failed to downloads the model due to security policy.  

Please follow the [link](https://github.com/pytorch/serve/blob/79e59fe2b68e611667e09fbf9c2a317c046d7da3/docs/management_api.md#encrypted-model-serving) to access encrypted model.

**Comment by zacnam** [comment] 2022-04-21 08:45
Still having issues with this - however we have narrowed down the cause of the issue to the following `FileUtils.copyURLToFile` within the `HttpUtils.copyURLToFile` [function](https://github.com/pytorch/serve/blob/a95ef13eb735efba6168ed485d7ab943f5e65ac3/frontend/archive/src/main/java/org/pytorch/serve/archive/model/s3/HttpUtils.java#L61)

As we're not currently using S3-SSE-KMS, the function defaults to the following [Apache function](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FileUtils.html#copyURLToFile(java.net.URL,%20java.io.File)), which can throw an error from a number of IO issues.

We will try with S3-SSE-KMS enabled and see if that fixes it.

**Comment by LewisDavidWong** [comment] 2022-04-21 19:18
I have encountered the exact same issue, I suspect it is due to TorchServe not handling s3 v4 signature URLs as previously mentioned in [issue 669](https://github.com/pytorch/serve/issues/669). I’m not sure why this issue was closed as it was not resolved.

**Comment by AndreasKleineberg** [comment] 2022-07-15 15:19
I am currently facing the same problem. Download via browser or using curl work fine, but torchserve cannot retrieve the model. I always get an HTTP 400 error.

**Comment by rmmr** [comment] 2023-05-05 14:32
Same here, quite the dealbreaker

**Comment by dgcnz** [comment] 2023-05-09 15:59
Any updates on this issue?

**Comment by cfculhane** [comment] 2023-06-05 10:12
Also facing this error - would be great if this could be fixed!

**Closed** 2023-06-15 22:31 UTC
Labels: bug, support, p0
