### ISSUE TITLE
pom.xml file has references to MXNet server

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#22] opened 2020-02-12 21:53 UTC
See https://github.com/pytorch/serve/blob/master/serving-sdk/pom.xml

This appears to be related to the `serving-sdk` component specifically. I'm assuming we don't want a bunch of references to MXNet Model Server or its source control in the project.

Is this SDK component going to be part of the final project? If not, is it something that can be cut, rather than leaving old stuff around?

**Comment by adityabindal** [comment] 2020-04-23 15:57
Duplicate of #179

**Closed by adityabindal** 2020-04-23 15:57 UTC
Labels: v1.0
