### ISSUE TITLE
Add support for custom metrics in /metrics endpoint and Prometheus

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#1092] opened 2021-05-22 04:47 UTC
The support for getting the [custom metrics](https://github.com/pytorch/serve/blob/master/docs/metrics.md#custom-metrics-api) via the /metrics endpoint for viewing via in dashboards using  [Prometheus + Grafana](https://github.com/pytorch/serve/blob/master/docs/metrics_api.md#prometheus-server).

**Comment by msaroufim** [comment] 2022-05-04 03:54
Duplicate of #1492

**Closed by msaroufim** 2022-05-04 03:54 UTC
Labels: enhancement
