### ISSUE TITLE
Reregistering model returns 'Model file already exist' after unregistering

### ISSUE THREAD

**Issue by alexwong** [pytorch/serve#279] opened 2020-04-28 20:53 UTC
I noticed the following behavior when doing some testing. I'm starting an instance and registering a model via S3 and then unregistering it. I then check the list of models to make sure it's empty again and trying to reregister the same model with the same S3 link but am getting 'Model file already exists".

To reproduce:

Register the model:
`
curl -X POST "http://localhost:8081/models?url=https://torchserve.s3.amazonaws.com/mar_files/squeezenet1_1.mar"
`

Unregister it:
`
curl -X DELETE "http://localhost:8081/models/squeezenet1_1"
`

List all models, this should return an empty list:
`
curl -X GET "http://localhost:8081/models/"
`

And try to register the same model again.
`
curl -X POST "http://localhost:8081/models?url=https://torchserve.s3.amazonaws.com/mar_files/squeezenet1_1.mar"
`

This returns a 500 error with 'Model file already exists squeezenet1_1.mar'. But registering with just the mar file name and not the S3 link works (model is successfully registered again). Is this an issue with the snapshot feature @mycpuorg @vdantu?

**Comment by chauhang** [comment] 2020-04-29 00:18
Duplicate of #160

**Closed** 2020-06-10 00:04 UTC
Labels: bug

**Comment by reeve02** [comment] 2024-05-29 13:29
Hello,

I'm dealing with similar issue.
The difference is that I use a model_file that is not in .mar format by following this example (https://github.com/pytorch/serve/tree/master/examples/large_models/Huggingface_accelerate/llama) which use `torch-model-archiver` with `--archive-format no-archive`

I'm using LLM from huggingface and try to deploy it with pytorch serve.

Registering model the first time 
`curl -X POST  "http://localhost:8081/models?url=file://server/model_store/seallm-7b"`
returned:
` "status": "Model "seallm-7b" Version: 1.0 registered with 0 initial workers. Use scale workers API to add workers for the model.`

Deleting model file the first time returned:
`"status": "Model \"seallm-7b\" unregistered"`

Trying to register it again returned:
`"code": 500,
  "type": "InternalServerException",
  "message": "Model file already exists seallm-7b"`

Using `curl http://localhost:8081/models/` returned:
`"models": []`

I already tried changing the model_store and the model name by adding `-2` suffix but it still returns:
`"code": 500,
  "type": "InternalServerException",
  "message": "Model file already exists seallm-7b-2"`
  
 Since the issue persists, I'm wondering if the previous fix only applies to .mar files
