### ISSUE TITLE
Custom pip package installation failed

### ISSUE THREAD

**Issue by graviraja** [pytorch/serve#652] opened 2020-08-26 11:41 UTC
Trying to get a model working with the external libraries in a requirements.txt added to the mar file following the documentation.

## Context

* torchserve version: 0.2.0
* torch version: 1.6.0
* torchvision version [if any]:
* torchtext version [if any]: 0.7.0
* torchaudio version [if any]:
* java version: 11.0.8
* Operating System and version: Ubuntu 18.04

## Your Environment

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: Custom
* What kind of model is it e.g. vision, text, audio?: text classification
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: Local model
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: yes
* Link to your project [if any]:

## Expected Behavior

Model should load properly and inference should work

## Current Behavior

Unable to install / load the python package

## Steps to Reproduce

1.  DOCKER_BUILDKIT=1 docker build --file Dockerfile -t torchserve:latest .
2.  docker run -it -p 8080:8080 -p 8081:8081 -v $(pwd)/model_store:/home/model-server/model-store -v $(pwd)/config.properties:/home/model-server/config.properties torchserve:latest bash
3.   torchserve --start --model-store model-store --models custom=custom.mar --ts-config config.properties

## Failure Logs [if any]

```code
model-server@60095f54e599:~$ torchserve --start --model-store model-store --models custom=custom.mar --ts-config config.properties
model-server@60095f54e599:~$ 2020-08-26 11:22:23,638 [INFO ] main org.pytorch.serve.ModelServer -
Torchserve version: 0.2.0
TS Home: /home/venv/lib/python3.6/site-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 12
Max heap size: 30688 M
Python executable: /home/venv/bin/python3
Config file: config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://127.0.0.1:8082
Model Store: /home/model-server/model-store
Initial Models: custom=custom.mar
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Prefer direct buffer: false
Custom python dependency for model allowed: true
Metrics report format: prometheus
Enable metrics API: true
2020-08-26 11:22:23,687 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: custom.mar
2020-08-26 11:22:28,391 [INFO ] main org.pytorch.serve.archive.ModelArchive - eTag f4f8d74274f24e8b99441bb3e927d0c6
2020-08-26 11:22:28,404 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model custom
2020-08-26 11:22:28,404 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model custom
2020-08-26 11:22:28,404 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model customloaded.
2020-08-26 11:22:29,125 [WARN ] main org.pytorch.serve.ModelServer - Failed to load model: custom.mar
org.pytorch.serve.archive.ModelException: Custom pip package installation failed for custom
        at org.pytorch.serve.wlm.ModelManager.setupModelDependencies(ModelManager.java:190)
        at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:125)
        at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:213)
        at org.pytorch.serve.ModelServer.start(ModelServer.java:308)
        at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:104)
        at org.pytorch.serve.ModelServer.main(ModelServer.java:85)
2020-08-26 11:22:29,130 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2020-08-26 11:22:29,220 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8080
2020-08-26 11:22:29,220 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2020-08-26 11:22:29,221 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://0.0.0.0:8081
2020-08-26 11:22:29,222 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2020-08-26 11:22:29,223 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://127.0.0.1:8082
Model server started.
2020-08-26 11:22:29,317 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:60095f54e599,timestamp:1598440949
2020-08-26 11:22:29,318 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:490.07086181640625|#Level:Host|#hostname:60095f54e599,timestamp:1598440949
2020-08-26 11:22:29,318 [INFO ] pool-2-thread-1 TS_METRICS - DiskUsage.Gigabytes:444.0924186706543|#Level:Host|#hostname:60095f54e599,timestamp:1598440949

```

### requirements.txt
```code
transformers==3.0.2
```

### config.properties
```code
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
default_workers_per_model=1
install_py_dep_per_model=true
```

Thanks for the help !!!

**Comment by harshbafna** [comment] 2020-08-26 11:46
Duplicate of #628. Please use the updated Dockerfile from PR #635.

**Comment by graviraja** [comment] 2020-08-26 12:06
@harshbafna  I am using the latest one only which contains `python3-distutils`. Here is the content of the Dockerfile

```code
ARG BASE_IMAGE=ubuntu:18.04

FROM ${BASE_IMAGE} AS compile-image

ENV PYTHONUNBUFFERED TRUE

RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    ca-certificates \
    g++ \
    python3-dev \
    python3-distutils \
    python3-venv \
    openjdk-11-jre-headless \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && cd /tmp \
    && curl -O https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py

RUN python3 -m venv /home/venv

```

**Comment by harshbafna** [comment] 2020-08-26 12:54
@graviraja : The `python3-distutils` package  has been added to the final runtime image as well in the PR #635.

Could you please recreate your image using the docker file from the above PR and try again?

You can also check if the package is available by using the following command on docker container shell :

```
apt list --installed | grep python3-distutils
```

**Comment by graviraja** [comment] 2020-08-27 10:39
Hi @harshbafna 

This was the output of the command

```code
model-server@405ab2e97958:~$ apt list --installed | grep python3-distutils

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

model-server@405ab2e97958:~$
```

These are the following steps I am using in order to build the docker image. (please let me know if I am doing anything wrong)

1. Pull the latest repo. (I am using master branch)
2. These are the contents of the Dockerfile 
```code
ARG BASE_IMAGE=ubuntu:18.04

FROM ${BASE_IMAGE} AS compile-image

ENV PYTHONUNBUFFERED TRUE

RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    ca-certificates \
    g++ \
    python3-dev \
    python3-distutils \
    python3-venv \
    openjdk-11-jre-headless \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && cd /tmp \
    && curl -O https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py

RUN python3 -m venv /home/venv

ENV PATH="/home/venv/bin:$PATH"

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN update-alternatives --install /usr/local/bin/pip pip /usr/local/bin/pip3 1

# This is only useful for cuda env
RUN export USE_CUDA=1

RUN pip install --no-cache-dir torch torchvision torchtext torchserve torch-model-archiver

# Final image for production
FROM ${BASE_IMAGE} AS runtime-image

ENV PYTHONUNBUFFERED TRUE

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    python3 \
    openjdk-11-jre-headless \
    && rm -rf /var/lib/apt/lists/* \
    && cd /tmp

COPY --from=compile-image /home/venv /home/venv

ENV PATH="/home/venv/bin:$PATH"

RUN useradd -m model-server \
    && mkdir -p /home/model-server/tmp

COPY dockerd-entrypoint.sh /usr/local/bin/dockerd-entrypoint.sh

RUN chmod +x /usr/local/bin/dockerd-entrypoint.sh \
    && chown -R model-server /home/model-server

COPY config.properties /home/model-server/config.properties
RUN mkdir /home/model-server/model-store && chown -R model-server /home/model-server/model-store

EXPOSE 8080 8081

USER model-server
WORKDIR /home/model-server
ENV TEMP=/home/model-server/tmp
ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh"]
CMD ["serve"]
```
3. Building the docker image

```
DOCKER_BUILDKIT=1 docker build --no-cache --file Dockerfile -t torchserve:latest .
```

4. Running the container

```
docker run -tid -p 8080:8080 -p 8081:8081 torchserve:latest
```

5. Entering the bash terminal & running the command you provided

```
docker exec -it suspicious_ardinghelli /bin/bash

model-server@405ab2e97958:~$ apt list --installed | grep python3-distutils

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

model-server@405ab2e97958:~$
```

6. Running pip command

```
model-server@405ab2e97958:~$ pip show trochserve
Traceback (most recent call last):
  File "/home/venv/bin/pip", line 7, in <module>
    from pip import main
  File "/home/venv/lib/python3.6/site-packages/pip/__init__.py", line 29, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/venv/lib/python3.6/site-packages/pip/utils/__init__.py", line 23, in <module>
    from pip.locations import (
  File "/home/venv/lib/python3.6/site-packages/pip/locations.py", line 9, in <module>
    from distutils import sysconfig
ImportError: cannot import name 'sysconfig'
```
7. Running torchserve without pip

```
model-server@405ab2e97958:~$ torchserve -v
TorchServe Version is 0.2.0
model-server@405ab2e97958:~$
```

**Comment by harshbafna** [comment] 2020-08-27 11:06
@graviraja: As indicated in my last command, this is a known issue in the Dockerfile available in the master branch and hence you need to use the Dockerfile from #635 (which is yet to be merged to the master branch)

**Comment by harshbafna** [comment] 2020-09-04 04:35
Closing due to inactivity.

**Closed by harshbafna** 2020-09-04 04:35 UTC
Labels: duplicate, triaged_wait
