### ISSUE TITLE
TorchScript model KeyError: 'modelFile'

### ISSUE THREAD

**Issue by ashokei** [pytorch/serve#541] opened 2020-07-18 00:16 UTC
TorchScript model archive was working before, fails with new update. According to documentation, modelFile is optional for torchscript models.

2020-07-17 16:41:01,070 [INFO ] epollEventLoopGroup-4-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2020-07-17 16:41:01,070 [INFO ] W-9000-resnet50_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     model_file = self.manifest['model']['modelFile']
2020-07-17 16:41:01,070 [INFO ] W-9000-resnet50_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - KeyError: 'modelFile'

**Comment by ashokei** [comment] 2020-07-18 00:45
have a PR https://github.com/pytorch/serve/pull/540

**Comment by harshbafna** [comment] 2020-07-18 01:19
Duplicate of #516

**Closed** 2020-07-18 01:58 UTC
Labels: duplicate
